com-lihaoyi/scalatags

scalatags/shared/src/main/scala/scalatags/generic/Styles.scala
Previously, max-height, max-width, min-height, and min-width were not PixelStyles. They are now, and they also provide predefined values according to MDN.
=> max|min-width|height are now PixelStyles with more predefined possible values

readme/Readme.scalatex
styles should be inserted into a style tag, as far as I know
=> typo fix 'script' -> 'style'

scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala
Fix for #93 
NOTE: there is one failing test. I checked master and it fails there as well, so it does not appear to be a regression introduced  by this change.
The failing test is:
```
[info] Failures:
[info] 44/96   scalatags.jsdom.DomTests.basic.styles
[info]       		utest.AssertionError: styleAttr == "color: red; float: left; background-color: yellow;"
[info]       		styleAttr: String = color: red; float: left; background-color: yellow;
```
=> added missing default values for empty attributes, fix for #93

scalatags/js/src/main/scala/scalatags/jsdom/SvgTags.scala, scalatags/shared/src/main/scala/scalatags/generic/SvgTags.scala, scalatags/shared/src/main/scala/scalatags/text/SvgTags.scala
http://www.w3.org/TR/SVG/extend.html#ForeignObjectElement
The "foreignobject" spelling causes this tag not to work in at least
Firefox.
=> Correct name to foreignObject

scalatags/shared/src/main/scala/scalatags/text/Builder.scala
=> fix compiler warning

scalatags/js/src/main/scala/scalatags/JsDom.scala, scalatags/shared/src/main/scala/scalatags/Text.scala, scalatags/shared/src/main/scala/scalatags/generic/Bundle.scala, scalatags/shared/src/test/scala/scalatags/generic/ExampleTests.scala
Addresses issue #86 by modifying `import short._` to work properly in the scope that the docs suggest.
Formerly, the test `'manualImports` was defined after an `import bundle.all._`, allowing errors in the implementation to get through.
Note that the example from the docs that imported:
``` 
import bundle.{attrs => attr, styles => css, _}
import bundle.tags._ 
```
Now requires two additional imports:
```
import bundle.implicits._
import scalatags.DataConverters._ 
```
=> Fix for short._ and manual imports.

scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala
`enctype` seemed to be missing - I think this will add it.
=> added enctype for forms

build.sbt, scalatags/js/src/main/scala/scalatags/JsDom.scala, scalatags/shared/src/main/scala/scalatags/DataTypes.scala, scalatags/shared/src/main/scala/scalatags/Text.scala, scalatags/shared/src/main/scala/scalatags/generic/Bundle.scala, scalatags/shared/src/main/scala/scalatags/generic/Core.scala, scalatags/shared/src/main/scala/scalatags/generic/Util.scala, scalatags/shared/src/main/scala/scalatags/stylesheet/StyleSheet.scala
This is a pull request that implements some code cleanup (as well as removing depreciations, which will matter for Scala 2.12)
- Syntax cleanup (specified return parameters for implicit def)
- Depreciation (changed view bounds to context bounds)
- Removed unused imports
- Added imports for advanced language features
- Added extra warning flags to Scalac
=> Code cleanup

scalatags/js/src/main/scala/scalatags/JsDom.scala, scalatags/shared/src/main/scala/scalatags/Text.scala, scalatags/shared/src/main/scala/scalatags/generic/Bundle.scala, scalatags/shared/src/test/scala/scalatags/generic/ExampleTests.scala
Add Data Converters to the `implicits` import. I don't see why anyone would want to `import implicits._` but not also `import DataConverters._`. This addresses a small part of #119
=> Data converters in implicits

scalatags/shared/src/main/scala/scalatags/Escaping.scala, scalatags/shared/src/main/scala/scalatags/Text.scala, scalatags/shared/src/main/scala/scalatags/package.scala, scalatags/shared/src/main/scala/scalatags/text/Builder.scala
Improve the rendering performance by reducing creating of intermediate data structures (mainly StringBuilders) and other minor tweaks.
Key change is to change the building of attributes from generating the value string immediately during the building phase to returning an ```AttrValueSource``` so that this can be rendered directly to the output string builder.
Also replaced the Regex based ```validAttrName``` with a faster hand-coded solution (its a simply regex) - this version is significantly faster and has no garbage churn.
Escaping.escape has also been rewritten to avoid intermediate String creation and improve performance.
The ```Builder``` increment method creates ClassTag instances on every invocation, replaced with a pair of method that hard-code the array types.
=> Performance improvements to rendering

build.sbt
It is currently on 0.8.2 and other projects are already on the 0.9.x version.
Can't have other dependencies upgraded as scalatags is still on 0.8.x.
#128
=> Upgrade scala-js-dom dependency to 0.9.1

scalatags/shared/src/main/scala/scalatags/generic/Styles.scala
I did not see a contribution guide in this repository, so please let me know if I'm missing something or you would prefer different styles.
I opened #161 regarding this. Discussion can be there or here.
I am trying to set vertical alignment for non-text items in one of my styles, and while there are both workarounds as well as other ways to do this, I would like to have parity with the CSS standard on this.
These two values are listed on [MDN: vertical-align](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align), and in the CSS level 1 and level 2 W3C specs.
```
vertical-align: top;
vertical-align: bottom;
```
=> add top and bottom for vertical-align

scalatags/shared/src/main/scala/scalatags/generic/SvgAttrs.scala
`SvgAttrs` lacks two important attributes for `<radialGradient>` tag namely `fx` and `fy`.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fx
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fy
=> Radial gradient focus point attributes

scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala
This PR just adds the defer attribute for scripts. Documentation has been extracted from the MDN (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script).
=> Add defer attribute for scripts

scalatags/src/scalatags/generic/Core.scala
I've tried to write an API which would only accept objects which render to standalone `dom.Element`s, yet none of the `JsDom` tags conformed to expected `Frag[dom.Element, dom.Element]` type. This seems to be fixed by the proposed change. Further simplifications may be possible, as `+FragT` in `generic.TypedTag` becomes pretty obsolete then. I didn't push too far though and settled for a more compatible change for now.
=> More specific Frag type for typed tags

scalatags/js/src/scalatags/JsDom.scala
Related to: https://github.com/lihaoyi/scalatags/pull/193
With both of these in place, rendered and unrendered element tags would conform to `Frag[dom.Element, dom.Element]`.
=> More specific Frag type for bound nodes

scalatags/js/src/scalatags/JsDom.scala, scalatags/src/scalatags/generic/Bundle.scala
This PR addresses 2 issues with ScalaJS api.  
They are very small so I didn't separate them... Will do if needed.
In Text api, `AttrValue` can only be `String`? as far as I understood.
But in JsDom api it can be almost any type?
Anyways, currently you can't abstract over `AttrPair`s in JsDom api.  
Neither of these compiles:
```scala
import scalatags.JsDom.all._
val a1: AttrPair = required
val a2: AttrPair = tpe := "checkbox"
Seq[AttrPair](required, tpe := "checkbox")
```
See https://scalafiddle.io/sf/f8vAr2s/1
This doesn't compile:
```scala
def component(frg: Frag) =
div(frg)
component(
raw("")
)
```
Currently it `extends Modifier` and not `Frag`.
=> Improve AttrPair alias. Make jsdom RawFrag extend Frag

project/Constants.scala
Is the website at https://com-lihaoyi.github.io/scalatags/ generated from this repo? by looking at [`Readme.scalatex`](https://github.com/com-lihaoyi/scalatags/blob/6f934f0d611ee4d3b59f69fa2081f5b28f24ebe3/readme/Readme.scalatex) it seems it does, how come the advertised version on the site is `0.8.2` if this value right here points to `0.8.1`, in any case shouldn't this be updated to latest `0.9.4`?
=> Bump advertised version to 0.9.4

scalatags/src/scalatags/generic/Attrs.scala
This MR just adds the `async` attribute for scripts.
Documentation has been extracted from the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)
=> Add async attribute for scripts

scalatags/js/src/scalatags/JsDom.scala
- `classList.add("")` throws an exception that is somehow swallowed.
=> Fix for empty string class name

build.sc
There were two Mima issues that popped up after https://github.com/com-lihaoyi/scalatags/commit/1724d9b4f219088103b69e43ff3445f7f2f4633d
1. ~It looks like we were hitting on
lightbend/mima#693 which has been fixed,
but not released yet. Therefore I bumped down to 3.1.0 to make Mima
happy for now. After the next release we can update Mima and then
update the Scala version as well.~
2. There is no `scalatags_native0.4_3` published yet, ~so the easiest fix
for now was to just remove Mima from the native stuff. If there is a
cleaner way to do this, let me know.~ So this removes the Mima check from the native and Scala 3 combo.
EDIT: Just turn of Mima for Scala 3 for now.
=> fix: mima issues in build definition

readme/Readme.scalatex
In Scala 2 you could use a `def` to define your `cls`s, but in Scala 3
the implementation is only looking for `valDef`s in the file, meaning
that `def`s will no longer work. This makes sure the docs don't mention
using `def`s and instead focus the verbiage on `val`s.
=> docs: make reference to stylesheet `val`s clear

readme/Readme.scalatex, scalatags/src-3/scalatags/stylesheet/SourceClasses.scala, scalatags/test/src/scalatags/generic/StyleSheetTests.scala
In Scala 2 the macro for SourceClasses captures both `def`s and `val`s where currently the Scala 3 implementation will only capture `val`s. This change updates the Scala 3 `SourceClasses` to ensure parity with the Scala 2 implementation making sure to also capture `def` classes.
Fixes #257
=> fix: ensure defs are captured in Scala 3 stylesheets
